config/routes.rb
Beatfinder::Application.routes.draw do |map|
  devise_for :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/signup" => "devise/registrations#new"
  end
  
  resources :users do
    resources :playlists
  end

  resources :songs do
    get :recent, :on => :collection
  end

  resources :sites do
    resources :songs
  end
  
  resources :playlists do
    resources :items, :controller => "playlist_items"
    get :load, :on => :member
  end

  root :to => "songs#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :playlists, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_box.html.haml
- if user_signed_in?
  = link_to "Logout", logout_path
- else
  = link_to "Login", login_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Username
    %th email
    %th

  - @users.each do |user|
    %tr
      %td= user.username
      %td= user.email
      %td= link_to 'Show', user

app/views/users/show.html.haml
%p
  %b Username:
  = @user.username

%p
  %b Email:
  = @user.email

%p
  %b Playlists:
  %ol
    - @user.playlists.each do |playlist|
      %li= link_to playlist.name, playlist

= link_to 'Back', users_path