config/routes.rb
Beatfinder::Application.routes.draw do |map|
  devise_for :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/signup" => "devise/registrations#new"
  end
  
  resources :users do
    resources :playlists
  end

  resources :songs do
    get :recent, :on => :collection
  end

  resources :sites do
    resources :songs
  end
  
  resources :playlists do
    resources :items, :controller => "playlist_items"
    get :load, :on => :member
  end

  root :to => "songs#index"

end

app/models/playlist_item.rb
class PlaylistItem < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist, :touch => true
  acts_as_list :scope => :playlist

  def css_selector
    "#playlist_item_#{id}"
  end
end

app/controllers/playlist_items_controller.rb
class PlaylistItemsController < ApplicationController
  respond_to :js
  layout nil

  before_filter :find_playlist
  before_filter :find_playlist_item, :only => [:update, :destroy]
  
  def create
   @playlist_item = @playlist.items.create(:song_id => params[:song_id])
   respond_with @playlist_item
  end

  def update
    @playlist_item.insert_at(params[:position])
    respond_with @playlist_item
  end

  def destroy
    @playlist_item.destroy
    respond_with @playlist_item
  end
  
  private
  
  def find_playlist
    if !user_signed_in? || params[:playlist_id] == Playlist::CURRENT
      @playlist = current_playlist
    else
      @playlist = current_user.playlists.find(params[:playlist_id])
    end
  end

  def find_playlist_item
    @playlist_item = @playlist.items.find(params[:id])
  end
end

app/helpers/playlist_items_helper.rb
module PlaylistItemsHelper
end

app/views/playlist_items/_item.html.haml
%div[item]
  %p #{link_to item.song.title, item.song} by #{item.song.artist}
  %p
    #{link_to_function 'play', "playlist.load(#{item.id})"} - 
    #{link_to 'download', song_path(item.song, :format => 'mp3')} - 
    #{link_to 'remove', playlist_item_path(item.playlist, item), :method => :delete, :remote => true} 
  :javascript
    $("#{item.css_selector}").data(#{item.song.to_json});

app/views/playlist_items/create.js.erb
<% if @playlist_item.position == 1 %>
$('#empty').hide();
<% end %>

var item = $("<%= escape_javascript( render :partial => "item", :object => @playlist_item ) %>");
item.hide();
$('#items').append(item);
item.effect('highlight', {}, 500);

<% if @playlist_item.position == 1 %>
playlist.load(<%= @playlist_item.id %>);
<% end %>

app/views/playlist_items/destroy.js.erb
var item = $('<%= @playlist_item.css_selector %>');
item.hide('highlight', {}, 500, function() { item.remove() });

<%- if @playlist.items.count == 0 %>
  $('#empty').show();
<%- end %>

app/views/playlist_items/update.js.erb
$('<%= @playlist_item.css_selector %>').effect('highlight', {}, 500);