config/routes.rb
Beatfinder::Application.routes.draw do |map|
  devise_for :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/signup" => "devise/registrations#new"
  end
  
  resources :users do
    resources :playlists
  end

  resources :songs do
    get :recent, :on => :collection
  end

  resources :sites do
    resources :songs
  end
  
  resources :playlists do
    resources :items, :controller => "playlist_items"
    get :load, :on => :member
  end

  root :to => "songs#index"

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  CURRENT = 'current'

  belongs_to :user
  has_many :items, :class_name => "PlaylistItem", :order => "position ASC", :include => :song, :dependent => :destroy
  has_many :songs, :through => :items, :order => "position ASC"

  def anonymous?
    self.user.nil?
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  respond_to :html, :json, :js

  before_filter :find_playlist, :only => [:show, :load, :edit, :update, :destroy]

  # GET /playlists
  def index
    @playlists = Playlist.all
    respond_with @playlists
  end

  # GET /playlists/1
  def show
    respond_with @playlist
  end

  # GET /playlists/1/load
  def load
    self.current_playlist = @playlist
    respond_with @playlist
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
    respond_with @playlist
  end

  # GET /playlists/1/edit
  def edit
    respond_wtih @playlist
  end

  # POST /playlists
  def create
    @playlist = Playlist.new(params[:playlist])
    flash[:notice] = 'Playlist was successfully created.' if @playlist.save
    respond_with @playlist
  end

  # PUT /playlists/1
  def update
    @playlist.update_attributes(params[:playlist])
    respond_with @playlist
  end

  # DELETE /playlists/1
  def destroy
    flash[:notice] = 'Playlist was successfully destroyed.' if @playlist.destroy
    respond_with @playlist
  end

  private

  def find_playlist
    @playlist = params[:id] == Playlist::CURRENT ? current_playlist : Playlist.find(params[:id])
  end

end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.haml
= semantic_form_for @playlist do |f|
  = f.inputs :name, :user
  = f.inputs do
    = f.input :songs, :as => :check_boxes, :collection => Song.active.inject({}){|songs,song| songs.merge(song.to_s => song.id)}
  = f.buttons

app/views/playlists/_playlist.html.haml
%h1{:id => "playlist_name"}= playlist.name
- unless playlist.anonymous?
  :javascript
    $('#playlist_name').editInPlace({
      url: "#{playlist_path(playlist)}",
      show_buttons: true,
      update_value: 'playlist[name]',
      saving_text: 'Saving...'
    });

#empty No songs... try adding one!
- unless playlist.songs.empty?
  :javascript
    $('#empty').hide();

#player 
  You need flash to listen to music.

#position_slider

#stats
  %span#time 0:00
  %span#load 0.0%

#controls
  = link_to_function '<<', 'playlist.previous()'
  |
  = link_to_function 'play', 'playlist.play()'
  |
  = link_to_function 'pause', 'playlist.pause()'
  |
  = link_to_function '>>', 'playlist.next()'

:javascript
  var so = new SWFObject('/flash/player.swf','ply','0','0','9');
  so.addParam('allowfullscreen','false');
  so.addParam('allowscriptaccess','always');
  so.write('player');

#items= render :partial => "playlist_items/item", :collection => playlist.items
:javascript
  $('#items').sortable({
    axis: 'y',
    stop: function (event, ui) {
      var id = ui.item.attr('id').split('_')[2];
      $.ajax({
        url: "playlists/current/items/" + id,
        type: "PUT",
        data: {
          position: ui.item.index() + 1 
        },
        dataType: 'script'
      });
    }
  });

app/views/playlists/edit.html.haml
%h1 Editing playlist

= render 'form'

= link_to 'Show', @playlist
\|
= link_to 'Back', playlists_path

app/views/playlists/index.html.haml
%h1 Listing playlists

%table
  %tr
    %th Name
    %th User
    %th Songs
    %th
    %th
    %th

  - @playlists.each do |playlist|
    %tr
      %td= playlist.name
      %td= playlist.user_id
      %td= playlist.items.count
      %td= link_to 'Show', playlist
      %td= link_to 'Load', load_playlist_path(playlist), :remote => true
      %td= link_to 'Destroy', playlist, :confirm => 'Are you sure?', :method => :delete

app/views/playlists/load.js.erb
playlist.pause();

$('#empty').hide();
$('#items').html("<%= escape_javascript( render :partial => "playlist_items/item", :collection => @playlist.items ) %>");

app/views/playlists/new.html.haml
%h1 New playlist

= render 'form'

= link_to 'Back', playlists_path

app/views/playlists/new.js.erb
playlist.pause();

$('#empty').hide();
$('#items').emtpy();

app/views/playlists/show.html.haml
%p
  %b Name:
  = @playlist.name
%p
  %b User:
  - if @playlist.anonymous?
    Anonymous
  - else
    = link_to @playlist.user.username, @playlist.user
%p
  %b Songs:
  %ol
    - @playlist.songs.each do |song|
      %li= link_to song, song

= link_to 'Load', load_playlist_path(@playlist), :remote => true
|
= link_to 'Back', playlists_path