config/routes.rb
Beatfinder::Application.routes.draw do |map|
  devise_for :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/signup" => "devise/registrations#new"
  end
  
  resources :users do
    resources :playlists
  end

  resources :songs do
    get :recent, :on => :collection
  end

  resources :sites do
    resources :songs
  end
  
  resources :playlists do
    resources :items, :controller => "playlist_items"
    get :load, :on => :member
  end

  root :to => "songs#index"

end

app/models/site.rb
class Site < ActiveRecord::Base
  MP3_REGEX = /['"](http:\/\/[^"' ]+\.mp3)['"]/i

  has_many :songs, :dependent => :destroy

  scope :visible, where(:visible => true)
  scope :scanable, where(:scanable => true)

  validates_presence_of :name, :url, :resource_url
  validates_uniqueness_of :url, :resource_url

  def to_s
    name
  end

  def data_dir
    Rails.root.join "data/#{id}"
  end

  def song_urls
    URI.parse(resource_url).read.scan(MP3_REGEX).map(&:join).uniq
  end

  def collect
    FileUtils.mkdir_p data_dir

    song_urls.each do |url|
      begin
        songs.create(:url => url, :active => false)
      rescue Exception => ex
        logger.info "Site ##{id} - #{ex}"
      end
    end
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # GET /sites
  def index
    @sites = Site.all
  end

  # GET /sites/1
  def show
    @site = Site.find(params[:id])
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  def create
    @site = Site.new(params[:site])
    
    if @site.save
      redirect_to(@site, :notice => 'Site was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /sites/1
  def update
    @site = Site.find(params[:id])
    
    if @site.update_attributes(params[:site])
      redirect_to(@site, :notice => 'Site was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /sites/1
  def destroy
    @site = Site.find(params[:id]).destroy
    redirect_to(sites_url)
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<% semantic_form_for @site do |form| %>
  <%= form.inputs %>
  <%= form.buttons %>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Visible</th>
    <th>Scanable</th>
    <th>Url</th>
    <th>Resource url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= site.name %></td>
    <td><%= site.visible %></td>
    <td><%= site.scanable %></td>
    <td><%= site.url %></td>
    <td><%= site.resource_url %></td>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p>
  <b>Name:</b>
  <%= @site.name %>
</p>

<p>
  <b>Visible:</b>
  <%= @site.visible %>
</p>

<p>
  <b>Scanable:</b>
  <%= @site.scanable %>
</p>

<p>
  <b>Url:</b>
  <%= @site.url %>
</p>

<p>
  <b>Resource url:</b>
  <%= @site.resource_url %>
</p>


<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>